source 'https://rubygems.org'

gem 'rake'
gem 'rake_terraform'
gem 'rake_docker'
gem 'rake_circle_ci'
gem 'rake_github'
gem 'rake_ssh'
gem 'rake_gpg'
gem 'git'
gem 'os'
gem 'semantic'
gem 'rspec'
gem 'docker-api'
gem 'serverspec'
